name: MCP KQL Server CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  basic-validation:
    name: Basic Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Validate project structure
      run: |
        echo "Validating project structure"
        test -f pyproject.toml && echo "Found pyproject.toml"
        test -f README.md && echo "Found README.md"
        test -d mcp_kql_server && echo "Found mcp_kql_server directory"
        test -f mcp_kql_server/__init__.py && echo "Found package __init__.py"
        echo "All required files found"
    
    - name: Test package build
      run: |
        echo "Testing package build"
        python -m build
        echo "Package built successfully"
        ls -la dist/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: python-package-distributions
        path: dist/

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install quality tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
    
    - name: Check code formatting
      run: |
        echo "Checking code formatting"
        black --check mcp_kql_server/ || echo "Black formatting issues found (non-blocking)"
        isort --check-only mcp_kql_server/ || echo "Import sorting issues found (non-blocking)"
        flake8 mcp_kql_server/ --max-line-length=100 || echo "Linting issues found (non-blocking)"
        echo "Code quality checks completed"

  multi-platform-test:
    name: Platform Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.10', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Basic compatibility test
      shell: python
      run: |
        import sys
        import os
        
        print('Python', sys.version)
        print('Platform: ${{ matrix.os }}')
        
        # Basic file existence check
        files_to_check = [
            'mcp_kql_server',
            'mcp_kql_server/__init__.py',
            'pyproject.toml'
        ]
        
        for file_path in files_to_check:
            if os.path.exists(file_path):
                print('Found:', file_path)
            else:
                print('Missing:', file_path)
                sys.exit(1)
        
        print('Basic compatibility test passed')

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [basic-validation, code-quality, multi-platform-test]
    if: always()
    
    steps:
    - name: Print summary
      run: |
        echo "CI/CD Pipeline Summary"
        echo "======================"
        echo ""
        echo "Basic Validation: ${{ needs.basic-validation.result }}"
        echo "Code Quality: ${{ needs.code-quality.result }}"
        echo "Multi-Platform Test: ${{ needs.multi-platform-test.result }}"
        echo ""
        
        success_count=0
        if [ "${{ needs.basic-validation.result }}" = "success" ]; then
          success_count=$((success_count + 1))
        fi
        if [ "${{ needs.code-quality.result }}" = "success" ]; then
          success_count=$((success_count + 1))
        fi
        if [ "${{ needs.multi-platform-test.result }}" = "success" ]; then
          success_count=$((success_count + 1))
        fi
        
        echo "Success Rate: $success_count/3 jobs passed"
        
        if [ $success_count -eq 3 ]; then
          echo "All pipeline stages passed!"
          echo "Repository is ready!"
        else
          echo "Some jobs had issues but pipeline completed"
        fi

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [basic-validation, code-quality, multi-platform-test]
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true